services:
  gateway:
    build:
      context: ./
      dockerfile: platform/gateway/Dockerfile.Gateway
    ports:
      - "5000:8080"
    depends_on:
      - users
      - tasks
      - notifications
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  users:
    build:
      context: ./
      dockerfile: product/users/Dockerfile.Users
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  tasks:
    build:
      context: ./
      dockerfile: product/tasks/Dockerfile.Tasks
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  notifications:
    build:
      context: ./
      dockerfile: product/notifications/Dockerfile.Notifications
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
