FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy nuget.config and packages for local feeds
COPY ../../nuget.config ./
COPY ../../packages ./packages

# Copy and restore
COPY platform/gateway/src/Gateway.csproj ./
RUN dotnet restore ./Gateway.csproj

# Copy source and build
COPY platform/gateway/src .
WORKDIR /src
RUN dotnet build -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "Gateway.dll"]
