FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy nuget.config and packages for local feeds
COPY ../../nuget.config ./
COPY ../../packages ./packages

# Copy and restore
COPY product/tasks/src/Tasks.csproj ./
RUN dotnet restore ./Tasks.csproj

# Copy source and build
COPY product/tasks/src .
WORKDIR /src
RUN dotnet build -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "Tasks.dll"]
