FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy nuget.config and packages for local feeds
COPY ../../nuget.config ./
COPY ../../packages ./packages

# Copy and restore
COPY product/users/src/Users.csproj ./
RUN dotnet restore ./Users.csproj

# Copy source and build
COPY product/users/src .
WORKDIR /src
RUN dotnet build -c Release -o /app/build

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/build .
ENTRYPOINT ["dotnet", "Users.dll"]
